name: Website Check

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Download Code
        uses: actions/checkout@v4

      - name: Deployment Success
        run: echo "Website updated successfully"
